### ISSUE TITLE
Added servers do not show up in Servers List

### ISSUE THREAD

**Issue by TheOfficialBurner** [crocofied/CoreControl#24]
Hi 

I just have started a stack of my own. Added a server, but this servers is not shown in Servers list.
In Network section the servers are listed. 

Apart from the original compose.yml i have added traefik for ssl 

any idea on how to fix that? 
Thanks in Advance

**Comment by crocofied** [comment]
Hey,

can you please pull the latest images again and restart the application?
This was a post-release bug, which should have been fixed in the latest image

**Comment by TheOfficialBurner** [comment]
Hello, 

thanks for your quick reply. 
I did so but still getting the same error. i also deleted the image from local docker images before pulling it again.

**Comment by zarevskaya** [comment]
Hello, same error here.

I noticed that it was when I was editing a parameter that I had this problem.

Have a nice day !

**Comment by crocofied** [comment]
That's pretty strange. I have now tried one more thing I thought of to fix this, try deleting the stack and the images completely and restarting the application from scratch. Everything works perfectly on my pc and my server. If it still doesn't work for you after that, please send me the logs of the containers

![Image](https://github.com/user-attachments/assets/f71b948c-b0fa-4a9f-a58e-5ab1d879dada)

**Comment by TheOfficialBurner** [comment]
Yes, this is more specific, it happens after editing an entry ;)


> Hello, same error here.
> 
> I noticed that it was when I was editing a parameter that I had this problem.
> 
> ![Image](https://github.com/user-attachments/assets/7d0b33c6-d395-481b-be9c-6f493472a502)
> 
> Have a nice day !

**Comment by epcos71** [comment]
Same issue here... Servers are selectable for an application and visible in the network, but they are not available in the server list. Also in the application view not all apps are shown when I change to the view, clicking on  "Next >" and on "< Previous" shows then the full list.

**Comment by crocofied** [comment]
So the servers are displayed after they have been added, but after editing they are no longer displayed? Can you tell me which property this is the case with? And did you already have CoreControl running before v0.0.6 and are therefore still using the same database?

**Comment by TheOfficialBurner** [comment]
ok, i have startet from scratch and everything seems to work fine now. 
stopping and starting the stack and everything is still working as axpected. 


> That's pretty strange. I have now tried one more thing I thought of to fix this, try deleting the stack and the images completely and restarting the application from scratch. Everything works perfectly on my pc and my server. If it still doesn't work for you after that, please send me the logs of the containers
> 
> ![Image](https://github.com/user-attachments/assets/f71b948c-b0fa-4a9f-a58e-5ab1d879dada)

**Comment by TheOfficialBurner** [comment]
Thank you for your support. Great project 👍

**Comment by crocofied** [comment]
Thank you very much, feel free to open more issues if you have problems or feature ideas.

**Comment by TheOfficialBurner** [comment]
I have a few ideas for creating and editing servers if you are open to it?


> Thank you very much, feel free to open more issues if you have problems or feature ideas.

**Comment by crocofied** [comment]
> I have a few ideas for creating and editing servers if you are open to it?

Sure! Just open up a new issue as a feature request for a better overview
