### ISSUE TITLE
[Bug]: Unhandled exception related to prisma client

### ISSUE THREAD

**Issue by bstag** [crocofied/CoreControl#66]
### What happened?

Prisma client issue running on ARM64

### Steps to reproduce

Brand new docker compose and images never having been downloaded follow the instructions [here](https://corecontrol.xyz/installation). This is the error in the corecontrol-web-1 logs related to the missing prisma binary for ARM64

### Operating System

Windows

### Version

1

### Logs

```⨯ unhandledRejection:  [Error [PrismaClientInitializationError]: Prisma Client could not locate the Query Engine for runtime "linux-musl-arm64-openssl-3.0.x".  This happened because Prisma Client was generated for "linux-musl-openssl-3.0.x", but the actual deployment required "linux-musl-arm64-openssl-3.0.x".  Add "linux-musl-arm64-openssl-3.0.x" to `binaryTargets` in the "schema.prisma" file and run `prisma generate` after saving it:  generator client {    provider      = "prisma-client-js"    binaryTargets = ["native", "linux-musl-arm64-openssl-3.0.x"]  }  The following locations have been searched:    /app/node_modules/.prisma/client    /app/node_modules/@prisma/client    /tmp/prisma-engines    /app/prisma] {    clientVersion: '6.6.0',    errorCode: undefined,    retryable: undefined  } ```

**Comment by buildplan** [comment]
I have the same issue and created a similar bug report.  This was made almost exactly at the same time as I was making mine.. 

I guess these can be merged.

**Comment by crocofied** [comment]
Hey,

thank you for reporting. I will investigate this now further and hopefully release a new version with the fix in a few hours

**Comment by crocofied** [comment]
I pushed a fix to the latest images, could you please repull them and restart the applications. Unfortunately, I can't try it out because I don't have an ARM architecture here @buildplan @bstag

**Comment by buildplan** [comment]
Thanks. 

I'll try it in a couple of hours and let you know.

**Comment by bstag** [comment]
Still getting this error
```
[Error [PrismaClientInitializationError]: Prisma Client could not locate the Query Engine for runtime "linux-musl-arm64-openssl-3.0.x".
This happened because Prisma Client was generated for "linux-musl-openssl-3.0.x", but the actual deployment required "linux-musl-arm64-openssl-3.0.x".
Add "linux-musl-arm64-openssl-3.0.x" to `binaryTargets` in the "schema.prisma" file and run `prisma generate` after saving it:
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "linux-musl-arm64-openssl-3.0.x"]
}
```

This is the last line in the image layers
```
CMD ["sh" "-c" " export PRISMA_CLI_BINARY_TARGETS=$(case $(uname -m) in x86_64) echo linux-musl-openssl-3.0.x ;; aarch64) echo linux-musl-arm64-openssl-3.0.x ;; armv7l) echo linux-musl-arm-openssl-3.0.x ;; *) echo \"Unsupported architecture: $(uname -m)\" && exit 1 ;; esac) && npx prisma migrate deploy && npm start"]
```

**Comment by crocofied** [comment]
I have now added the binaryTargets into the prisma scheme. Can you please repull and restart again? @bstag

**Comment by bstag** [comment]
No more Prisma errors. I am no0 getting this when i try and log in. 
```
 ⨯ [Error: Error relocating /app/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node: unsupported relocation type 7] {

  code: 'ERR_DLOPEN_FAILED'
```

**Comment by crocofied** [comment]
Perfect, this was an error with the dependency bcrypt which is used to hash passwords. It apparently does not work on ARM based systems, I have now adjusted this. Can you try again now? (sorry for all the requests)

**Comment by bstag** [comment]
The error is not longer there and I can login with default information. 
Thank you.

**Comment by crocofied** [comment]
No problem and thank you very much for your help and time! As this seems to be fixed i will close this issue now

**Comment by buildplan** [comment]
Hi, Just to add thank you so much for the swift fix and can confirm I can log in now and going to start configuring it. 

PS. The version number still shows 1.0.0 instead of 1.0.1 in the GUI - not an issue, just thought I mention it.

**Comment by crocofied** [comment]
Perfect 👍Fixed the version number in the latest image!
